version: "3.9"
networks:
  default:
    name: "mattermostnw"
services:
  mattermost:
    container_name: mattermost
    image: "mattermost/mattermost-enterprise-edition:8.1.8"
    restart: "unless-stopped"
    depends_on:
      - "db"
    ports:
      - "8065:8065"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MM_SQLSETTINGS_DRIVERNAME: "postgres"
      MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mostest@db:5432/mattermost_test?sslmode=disable\u0026connect_timeout=10"
      MM_SERVICESETTINGS_LISTENADDRESS: ":8065"
      MM_SERVICESETTINGS_SITEURL: "http://localhost:8065"
      MM_SERVICESETTINGS_ENABLEDEVELOPER: "true"
      MM_PLUGINSETTINGS_ENABLEUPLOADS: "true"
      MM_LOGSETTINGS_CONSOLELEVEL: "DEBUG"
      MM_LOGSETTINGS_FILELEVEL: "DEBUG"
      MM_SERVICESETTINGS_ENABLELOCALMODE: "true"
      MM_FILESETTINGS_MAXFILESIZE: 123524266
      MM_PASSWORDSETTINGS_MINIMUMLENGTH: 5
      MM_SERVICESETTINGS_ENABLETUTORIAL: "false"
      MM_TEAMSETTINGS_TEAMMATENAMEDISPLAY: "full_name"
      MM_SERVICESETTINGS_ENABLEONBOARDINGFLOW: "false"
      MM_NATIVEAPPSETTINGS_APPDOWNLOADLINK: ""
  db:
    image: "postgres"
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: "mostest"
      POSTGRES_USER: "mmuser"
      POSTGRES_DB: "mattermost_test"
  qdrant-db:
    image: qdrant/qdrant:latest
    restart: "unless-stopped"
    ports:
      - 6333:6333
      - 6334:6334
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
